language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: FDnrcWgJI1Kb6rZG1+TjsczJIzhRodiOhyPQTY04Z8ceQf9iIZQestJ9fx0LB4dIA2vVM+d6tgDTyZ+kxX5vJAP/fCqSQ+J9TrGFNr+XukKfAKfPrjZkL68JH1TuMSceN92DwLQndmWauKV42nrsTLzUn1k1krnkn7a997AmMCLKAHmL0t98XxCFz73wRmnDuadG7l9CRaLA+RmNuRIt9VxnhOkrMZAHrkvKYzTnDfIbNk8Ko7MbHVB+837Qr8gteJuvULGDzJcpqIM5uc74BRWItizuea4COtwArKGnj+agmdEad6L1tpAeELPjLtDFVqevKiyGXap4HLjxHkQEoyLMjZIboNrksfK9siU3DRtbkUxZ/RRF1D9x0ppe2D6bqoDIi0nBL794vcPSPwBNBpCCPUXkcEf2eb1YrHR5kLwwBZdqxFlrtP38QcZSgHmz8a5QaCpPQx2Xaogju49Oy+/VQFQl2f8pq7Ndh5zsk5TtUNXv1lfMhXDBEc8lHbjEKT3YQnJ6odQxXSBTk0t6BuAF61A8ZMhIdppIFWw23rT2bX2GweY8fYEwlTya7AIhOe6wsuERqYJyDLg+DO3UxCZmiMWbWt61cnZYDx5Z4uzKeqTcXPb5u0b+gkdPhIgzORNStE9n2YMIUmXOtTNY2u4e4SvvEwmPgD0gYGywcoI=

    # FIREBASE_SECRET
    - secure: Xv5XclSBUaIeOT5bk/ESc2M8hTH+ONgQn0k7/j2EZQ0ZOd2hv30aSTUSABwg8mgofiwuiOZ2XWFKagODISdcWx4PpxsG6CNEKdjVyPGhJht6nBcsOtla52+RHRCmxL84MrPeNxXGd6Wec/+mi+UeKLZsrEXV+Qu2eX4h8esIWY1Bh2lvyouoonG6lK41v9jGHRCmHZxaMllAFSkCZP9xqFsNFgMlr7VJKgHgSAB13D7t1zTi//DLF9RP2PTW+iJVlX25AxSnZlP+pATfTamXYQXtii4Ea3k+FHst+13sFXnTbYXyxcYcNdmT/Hl5D6tIVptyl8nz9YoCrJLzmHJiriigt0p3Yk3rGFgpP5SvDn+KL229DnUms3+bEI5RR1S4s3JkaIGbU0uHYPK7k7nKvhAOHP/EUJywt3E1rcDjGmqmbgK6xZbJTqzJy/iJjMM3j7XnjmEKM4yLlGCjro4n3xIKOV7KfgsQ2/1eRJRTto0V+xubPtOAGH3+pbjDe6Kbccfq8tC6wIg7/q0AFqQq2f97l14b/hhec4Afz0khrjbsJ/kQBcITSA50Us3p5lYJb3ySLTpQ9mOkMj7fBxpfqCal3Zr6e9eWZ5Llhesx2JOidaaP6VBRxP2M0VnrL3HG39xQ/AbUBu07dRoKZBkKqZGXeQog5Fmvmmf5yxUKblI=
