language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: vae/rLs7Bk+Cy3fLlXatMti/JnIBN3bV+Dg9wMaQtQqPnVZLNQZEn7ySSJpL6auKcsFqywXF0Iihy1nGmNzsxJb9cuxVR2DVBKiEEAbcGPYHCXW6W7nWyjW6/i/4lhZvgKDrQLAi1SuiilrBEZ/0C2SQv9Wk0g4rf+N1YRxq9QpmROUVUPhPtl49teH+bmEuQeuSAfFArDM6tAqm0E6LykRQLtbB801cP+HpbHKLhQ3StwZjkI0Z7LJ4D6okNOO5RqGR/pA2ljIq7EcbS6/yU1kezXAVYhgql9jX/0tCg579OlGmLK58DzgqmK4hCuN9a2JCL07ZMa/rh/0v5t6oww4+fhMV44O016D/pRZgGcY5tjbsWVt5cWgoDj/pDNO+5idOPhwqrf/IQN0talrIwENOn9m+R8L8gEoLbOWaCb8Woj/q1HjvRIZ3EUmnlrE35xy1HP0qS+fcbnzr+8SiNEJDpzNIaOjXfDZm6hy/MmM2G8vJRL+ADr3gHs772H3twaYlQtqp5WJIyLwaD9iNBC4tLXdRDkQD2gz948eMUKfZ8ZBD6/nblxD50hLx2xHdS8aw1zQu8kFiMkOi9N7pc2KaVhFJy/AXY4rVBqX8stviP3zzBZv8Yq3X+9w3hBqUCGoFJ897sDEnSmIs0t2jLflVC55pfHV8GvHfIxFEivs=
    # FIREBASE SECRET
    - secure: pnuoShJjBkBKP2pkM/uKfY2lModOOwpaJVgawSosWxqWiAcz5OWNGIJU//hFvkC761coFvLmqGKByb7pyG0570Wle9y212PmZOwPzi//gabcny15nnRi5x+7ZYgGJlq1WjBkMjY7oqTkzh5UeEj4hqcVN1zTQCKsuMMoLJo07dmonO9Dp74Gd/c7EP5to8uf62m4aNPgexFuytUY0HC3ugT8SzCxczsVevLD6bV5rEIsu7VKPfTYtXZEzFPFIfZJYD/7FfG3lFnRgjxOkrqKRI+1j98FClAOkRt5a0/FoyXymBeL6Fp535mVjTCyM+lcsPWBTTklU0MvPwmGp0T1tyHTCpCLbV4hmv8Hg7XfwBBOeUEN/j/3t3SO/DlMc63vfqXg9HA7mWK56sfr9eK0mFNiG7WtjF8o+raUDqJ5l1A3GMGgyCcXSiPZZuyuo0Kv/sij7L3cNYWCLXknYaDGSeEv2if+whRKTrYo6LnEt200jJy9YGKS1ZuIT1/0JM7FzUrb0W5lVF5wsF4s9gEwD2NFenyYXOMI3B5wwBXGItN4thZ846/SrOyYlID+YfID1Pnfx4mfTt+Nnr253K22AiPx689DZUH1ZLwuVJtLPwdQrykC8rFuKwCxoX5mekdg28P41MLMy9N1R+8i81wgD7di1TR63JvRk1ce9RLUqeI=
